"""Empirical profiling of the raw Olist CSVs.

Nothing downstream assumes a schema from the dataset description. This module reads
the actual files and reports what is really in them: row counts, columns, dtypes,
null counts, primary key uniqueness and foreign key coverage.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pandas as pd

from src.config import RAW_FILES, Config

CANDIDATE_KEYS = {
    "customers": ["customer_id"],
    "geolocation": None,
    "order_items": ["order_id", "order_item_id"],
    "order_payments": ["order_id", "payment_sequential"],
    "order_reviews": ["review_id"],
    "orders": ["order_id"],
    "products": ["product_id"],
    "sellers": ["seller_id"],
    "product_category_translation": ["product_category_name"],
}

FOREIGN_KEYS = [
    ("orders", "customer_id", "customers", "customer_id"),
    ("order_items", "order_id", "orders", "order_id"),
    ("order_items", "product_id", "products", "product_id"),
    ("order_items", "seller_id", "sellers", "seller_id"),
    ("order_payments", "order_id", "orders", "order_id"),
    ("order_reviews", "order_id", "orders", "order_id"),
    ("products", "product_category_name", "product_category_translation", "product_category_name"),
]


def load_raw(config: Config) -> dict[str, pd.DataFrame]:
    frames = {}
    for name, filename in RAW_FILES.items():
        path = config.raw_dir / filename
        if not path.exists():
            raise FileNotFoundError(f"missing raw file: {path}")
        frames[name] = pd.read_csv(path)
    return frames


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def profile(config: Config) -> dict:
    frames = load_raw(config)
    tables = {}

    for name, frame in frames.items():
        path = config.raw_dir / RAW_FILES[name]
        key = CANDIDATE_KEYS.get(name)
        key_report = None
        if key:
            duplicated = int(frame.duplicated(subset=key).sum())
            key_report = {
                "columns": key,
                "unique": duplicated == 0,
                "duplicate_rows": duplicated,
            }
        tables[name] = {
            "file": RAW_FILES[name],
            "bytes": path.stat().st_size,
            "sha256": _sha256(path),
            "rows": int(len(frame)),
            "columns": list(frame.columns),
            "dtypes": {c: str(t) for c, t in frame.dtypes.items()},
            "null_counts": {c: int(n) for c, n in frame.isna().sum().items() if n > 0},
            "exact_duplicate_rows": int(frame.duplicated().sum()),
            "candidate_key": key_report,
        }

    fk_reports = []
    for child, child_col, parent, parent_col in FOREIGN_KEYS:
        child_values = frames[child][child_col]
        parent_values = set(frames[parent][parent_col].dropna().unique())
        non_null = child_values.dropna()
        orphans = non_null[~non_null.isin(parent_values)]
        fk_reports.append(
            {
                "child": f"{child}.{child_col}",
                "parent": f"{parent}.{parent_col}",
                "child_rows": int(len(child_values)),
                "child_nulls": int(child_values.isna().sum()),
                "orphan_rows": int(len(orphans)),
                "orphan_distinct_values": int(orphans.nunique()),
                "clean": bool(len(orphans) == 0),
            }
        )

    return {"tables": tables, "foreign_keys": fk_reports}


def to_markdown(report: dict) -> str:
    lines = ["# Raw data profile", ""]
    lines.append("Generated by `python run.py 1`. Every number below is read from the actual CSVs.")
    lines.append("")
    lines.append("## Tables")
    lines.append("")
    lines.append("| table | rows | columns | exact dup rows | key unique |")
    lines.append("| --- | ---: | ---: | ---: | --- |")
    for name, info in report["tables"].items():
        key = info["candidate_key"]
        key_state = "n/a" if key is None else ("yes" if key["unique"] else f"no ({key['duplicate_rows']} dup)")
        lines.append(
            f"| {name} | {info['rows']:,} | {len(info['columns'])} | {info['exact_duplicate_rows']:,} | {key_state} |"
        )

    lines.append("")
    lines.append("## Foreign keys")
    lines.append("")
    lines.append("| child | parent | child rows | nulls | orphans | clean |")
    lines.append("| --- | --- | ---: | ---: | ---: | --- |")
    for fk in report["foreign_keys"]:
        lines.append(
            f"| {fk['child']} | {fk['parent']} | {fk['child_rows']:,} | {fk['child_nulls']:,} "
            f"| {fk['orphan_rows']:,} | {'yes' if fk['clean'] else 'no'} |"
        )

    lines.append("")
    lines.append("## Columns and nulls")
    lines.append("")
    for name, info in report["tables"].items():
        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"`{info['file']}`, sha256 `{info['sha256'][:16]}...`")
        lines.append("")
        lines.append("| column | dtype | nulls |")
        lines.append("| --- | --- | ---: |")
        for col in info["columns"]:
            nulls = info["null_counts"].get(col, 0)
            lines.append(f"| {col} | {info['dtypes'][col]} | {nulls:,} |")
        lines.append("")
    return "\n".join(lines)


def run(config: Config) -> dict:
    report = profile(config)
    (config.reports_dir / "data_profile.json").write_text(json.dumps(report, indent=2))
    (config.reports_dir / "data_profile.md").write_text(to_markdown(report))
    return report
